/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemLogsRouteImport } from './routes/system-logs'
import { Route as SubSystemsRouteImport } from './routes/sub-systems'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentHubRouteImport } from './routes/agent-hub'
import { Route as IndexRouteImport } from './routes/index'

const SystemLogsRoute = SystemLogsRouteImport.update({
  id: '/system-logs',
  path: '/system-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SubSystemsRoute = SubSystemsRouteImport.update({
  id: '/sub-systems',
  path: '/sub-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/agent-hub',
  path: '/agent-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/settings': typeof SettingsRoute
  '/sub-systems': typeof SubSystemsRoute
  '/system-logs': typeof SystemLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/settings': typeof SettingsRoute
  '/sub-systems': typeof SubSystemsRoute
  '/system-logs': typeof SystemLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/settings': typeof SettingsRoute
  '/sub-systems': typeof SubSystemsRoute
  '/system-logs': typeof SystemLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-hub' | '/settings' | '/sub-systems' | '/system-logs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-hub' | '/settings' | '/sub-systems' | '/system-logs'
  id:
    | '__root__'
    | '/'
    | '/agent-hub'
    | '/settings'
    | '/sub-systems'
    | '/system-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentHubRoute: typeof AgentHubRoute
  SettingsRoute: typeof SettingsRoute
  SubSystemsRoute: typeof SubSystemsRoute
  SystemLogsRoute: typeof SystemLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-logs': {
      id: '/system-logs'
      path: '/system-logs'
      fullPath: '/system-logs'
      preLoaderRoute: typeof SystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-systems': {
      id: '/sub-systems'
      path: '/sub-systems'
      fullPath: '/sub-systems'
      preLoaderRoute: typeof SubSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-hub': {
      id: '/agent-hub'
      path: '/agent-hub'
      fullPath: '/agent-hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentHubRoute: AgentHubRoute,
  SettingsRoute: SettingsRoute,
  SubSystemsRoute: SubSystemsRoute,
  SystemLogsRoute: SystemLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
