/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as SystemLogsRouteImport } from './routes/system-logs'
import { Route as SubSystemsRouteImport } from './routes/sub-systems'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GeoTrackingRouteImport } from './routes/geo-tracking'
import { Route as AgentHubRouteImport } from './routes/agent-hub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentHubSlugRouteImport } from './routes/agent-hub_.$slug'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemLogsRoute = SystemLogsRouteImport.update({
  id: '/system-logs',
  path: '/system-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SubSystemsRoute = SubSystemsRouteImport.update({
  id: '/sub-systems',
  path: '/sub-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoTrackingRoute = GeoTrackingRouteImport.update({
  id: '/geo-tracking',
  path: '/geo-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/agent-hub',
  path: '/agent-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHubSlugRoute = AgentHubSlugRouteImport.update({
  id: '/agent-hub_/$slug',
  path: '/agent-hub/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/geo-tracking': typeof GeoTrackingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sub-systems': typeof SubSystemsRoute
  '/system-logs': typeof SystemLogsRoute
  '/vision': typeof VisionRoute
  '/agent-hub/$slug': typeof AgentHubSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/geo-tracking': typeof GeoTrackingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sub-systems': typeof SubSystemsRoute
  '/system-logs': typeof SystemLogsRoute
  '/vision': typeof VisionRoute
  '/agent-hub/$slug': typeof AgentHubSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-hub': typeof AgentHubRoute
  '/geo-tracking': typeof GeoTrackingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sub-systems': typeof SubSystemsRoute
  '/system-logs': typeof SystemLogsRoute
  '/vision': typeof VisionRoute
  '/agent-hub_/$slug': typeof AgentHubSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-hub'
    | '/geo-tracking'
    | '/reset-password'
    | '/settings'
    | '/sub-systems'
    | '/system-logs'
    | '/vision'
    | '/agent-hub/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-hub'
    | '/geo-tracking'
    | '/reset-password'
    | '/settings'
    | '/sub-systems'
    | '/system-logs'
    | '/vision'
    | '/agent-hub/$slug'
  id:
    | '__root__'
    | '/'
    | '/agent-hub'
    | '/geo-tracking'
    | '/reset-password'
    | '/settings'
    | '/sub-systems'
    | '/system-logs'
    | '/vision'
    | '/agent-hub_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentHubRoute: typeof AgentHubRoute
  GeoTrackingRoute: typeof GeoTrackingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SubSystemsRoute: typeof SubSystemsRoute
  SystemLogsRoute: typeof SystemLogsRoute
  VisionRoute: typeof VisionRoute
  AgentHubSlugRoute: typeof AgentHubSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-logs': {
      id: '/system-logs'
      path: '/system-logs'
      fullPath: '/system-logs'
      preLoaderRoute: typeof SystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-systems': {
      id: '/sub-systems'
      path: '/sub-systems'
      fullPath: '/sub-systems'
      preLoaderRoute: typeof SubSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo-tracking': {
      id: '/geo-tracking'
      path: '/geo-tracking'
      fullPath: '/geo-tracking'
      preLoaderRoute: typeof GeoTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-hub': {
      id: '/agent-hub'
      path: '/agent-hub'
      fullPath: '/agent-hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-hub_/$slug': {
      id: '/agent-hub_/$slug'
      path: '/agent-hub/$slug'
      fullPath: '/agent-hub/$slug'
      preLoaderRoute: typeof AgentHubSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentHubRoute: AgentHubRoute,
  GeoTrackingRoute: GeoTrackingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SubSystemsRoute: SubSystemsRoute,
  SystemLogsRoute: SystemLogsRoute,
  VisionRoute: VisionRoute,
  AgentHubSlugRoute: AgentHubSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
